var success =' <!DOCTYPE html>'
+' <head>'
+' '
+' </head>'
+' <body>'
+' <h1 align="center">'
+'   Success'
+' </h1>'
+' <p align="center">A verification email has been sent. Please click the link to verify your account</p>'
+' <p align="center">You will be redirected shortly</p>'
+' <script>'
+' setTimeout(function(){window.location.href="/"},5000)'
+' </script>'
+' </body>'

var registration = '<head>'
+ '  <style>'
+ '    input, label {'
+ '      display:block;'
+ '    }'
+ '  </style>'
+ '  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />'
+ '  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>'
+ '  <script>'
+ '  function submitForm(){'
+ '    var uname = document.getElementById("username").value;'
+ '    var pass = document.getElementById("password").value;'
+ '    var pass2 = document.getElementById("password2").value;'
+ '    var fname = document.getElementById("fname").value;'
+ '    var lname = document.getElementById("lname").value;'
+ '    var email = document.getElementById("email").value;'
+ ''
+ '    if(uname !="" && pass!="" && pass2!="" && fname!="" && lname!="" && email!=""){'
+ '      if (document.getElementById("password").value == document.getElementById("password2").value){'
+ '        $.post("register.js", $("#registerform").serialize(), function (status){'
+ '          if (status=="All good") window.location.href="/success";'
+ '        });'
+ '      }'
+ '      else alert("passwords do not match");'
+ '    }'
+ '    else alert("all fields are required");'
+ '  }'
+ '  function goToLogin(){'
+ '    window.location.href="/login";'
+ '  }'
+ '  </script>'
+ '</head>'
+ '<body>'
+ '  <form autocomplete="off" id="registerform" action="register.js" method="POST" >'
+ '    <div>'
+ '      <label for="username">Username:</label>'
+ '      <input type="text" id="username" name="uname"/><br>'
+ '    </div>'
+ '    <div>'
+ '      <label for="password">Password:</label>'
+ '      <input type="password" id="password" name="pass"/><br>'
+ '    </div>'
+ '    <div>'
+ '      <label for="password2">Confirm password:</label>'
+ '      <input type="password" id="password2" name="pass2"/><br>'
+ '    </div>'
+ '    <div>'
+ '      <label for="fname">First name:</label>'
+ '      <input type="text" id="fname" name="fname"/><br>'
+ '    </div>'
+ '    <div>'
+ '      <label for="lname">Last name:</label>'
+ '      <input type="text" id="lname" name="lname"/><br>'
+ '    </div>'
+ '    <div>'
+ '      <label for="email">Email:</label>'
+ '      <input type="email" id="email" name="email"/><br>'
+ '    </div>'
+ '      <input type="button" id="submit" value="Register" onclick="submitForm()" />'
+ '      <label style="display:inline" for="login">If you already have an account, please log in</label>'
+ '      <input style="display:inline" type="button" id="login" value="Login" onclick="goToLogin()" />'
+ '    </form>'
+ '</body>'

var login = '<!DOCTYPE html>'
+ '<head>'
+ '  <style>'
+ '    input, label {'
+ '      display:block;'
+ '    }'
+ '  </style>'
+ '  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />'
+ '  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>'
+ '  <script>'
+ '  localStorage.removeItem("status");'
+ ''
+ '  function submitForm(){'
+ '    var uname = document.getElementById("username").value;'
+ '    var pass = document.getElementById("password").value;'
+ ''
+ '    document.cookie = "loggedIn=; expires=Thu, 08 Aug 2019 00:00:01 GMT;  path=/";'
+ '    document.cookie = "admin=; expires=Thu,  08 Aug 2019 00:00:01 GMT;  path=/";'
+ '    alert(document.cookie);'
+ '    if(uname !="" && pass!=""){'
+ '      $.post("login.js", $("#loginform").serialize(), function (status){'
+ '        if (status==1) alert("Please verify your account before logging in");'
+ '        else if (status==2) alert("Your account has been banned");'
+ '        else if (status==3) alert("Username and password do not match");'
+ '        else if (status==0){'
+ '          alert("Welcome");'
+ '          document.cookie="loggedIn=yes; path=/";'
+ '          alert(document.cookie);'
+ '          window.location.href="home.html";'
+ '        }'
+ '        else if (status==4){'
+ '          alert("Welcome, admin");'
+ '          document.cookie="admin=yes; path=/";'
+ '          window.location.href="admin_controls.html";'
+ '        }'
+ '      });'
+ '    }'
+ '    else alert("All fields are required");'
+ '  }'
+ '  function goToRegister(){'
+ '    window.location.href="register";'
+ '  }'
+ '  </script>'
+ '</head>'
+ '<body>'
+ '  <form autocomplete="off" id="loginform" action="login.php" method="POST" >'
+ '    <div>'
+ '      <label for="username">Username:</label>'
+ '      <input type="text" id="username" name="uname"/><br>'
+ '    </div>'
+ '    <div>'
+ '      <label for="password">Password:</label>'
+ '      <input type="password" id="password" name="pass"/><br>'
+ '    </div>'
+ '      <input type="button" id="login" value="Login" onclick="submitForm()" />'
+ '      <label style="display:inline" for="register">If you don\'t have an account, please register: </label>'
+ '      <input style="display:inline" type="button" id="register" value="Register" onclick="goToRegister()" />'
+ '    </form>'
+ '</body>'

var home = '<head>'
+ '<style>'
+ '* {'
+ '  box-sizing: border-box;'
+ '}'
+ ''
+ 'body {'
+ '  font-family: Arial, Helvetica, sans-serif;'
+ '}'
+ ''
+ '.column {'
+ '  float: left;'
+ '  width: 25%;'
+ '  padding: 0 10px;'
+ '}'
+ ''
+ '.row {margin: 0 -5px;}'
+ ''
+ '.row:after {'
+ '  content: "";'
+ '  display: table;'
+ '  clear: both;'
+ '}'
+ ''
+ '.card {'
+ '  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);'
+ '  max-width: 300px;'
+ '  margin: auto;'
+ '  text-align: center;'
+ '  font-family: arial;'
+ '}'
+ ''
+ '.price {'
+ '  color: grey;'
+ '  font-size: 22px;'
+ '}'
+ ''
+ '.card button {'
+ '  border: none;'
+ '  outline: 0;'
+ '  padding: 12px;'
+ '  color: white;'
+ '  background-color: #000;'
+ '  text-align: center;'
+ '  cursor: pointer;'
+ '  width: 100%;'
+ '  font-size: 18px;'
+ '}'
+ ''
+ '.card button:hover {'
+ '  opacity: 0.7;'
+ '}'
+ ''
+ 'div {'
+ '  word-wrap: break-word;'
+ '}'
+ '@media screen and (max-width: 800px) {'
+ '  .column {'
+ '    width: 100%;'
+ '    display: block;'
+ '    margin-bottom: 20px;'
+ '  }'
+ '</style>'
+ '</head>'
+ '<body>'
+ '<h1 align="center">Homepage</h1>'
+ '<p align="center">That\'s it for now</p>'
+ '<div style="text-align: center;">'
+ '  <button align="center" onclick="location.href = \'/Online_Store/search.html\';">Search</button>'
+ '<div>'
+ '<div id="products"></div>'

module.exports = {registration, login, success, home}
